# Generated by Django 2.1.3 on 2018-11-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_post', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('enrollment_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='panas',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Respondent'),
        ),
    ]
