# Generated by Django 2.1.3 on 2018-11-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
