# Generated by Django 2.1.3 on 2018-11-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181111_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='panas',
            name='question',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='panas',
            name='answer',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
